### PR TITLE
Azure storage cpp: fix linter

### PR DESCRIPTION
**Pull request by ericLemanissier**

### CODE REVIEW

**Comment by ericLemanissier** [comment]
@samuel-emrys this should solve the linter error on your CCI PR

**Comment by samuel-emrys** [comment]
Thanks @ericLemanissier. Are these necessary to secure a merge? I'd prefer to keep this PR extremely minimal so it's obvious what it's for, rather than also making the necessary conan v2 changes at the same time - it would blur the scope of the PR and (potentially) trigger a requirement other v2 changes

**Comment by ericLemanissier** [comment]
Yes, your PR cannot be merged if the linters fail

**Comment by ericLemanissier** [comment]
Note that these changes do not provide conan V2 compatibility

**Comment by ericLemanissier** [comment]
friendly ping @samuel-emrys to be sure you get a notification for the two messages above ⬆️

**Comment by samuel-emrys** [comment]
@ericLemanissier sorry I was so slow on this. Looks like it's already gone in without the linting fixes so closing this off

**Pull request closed without merging**
